# Generated by Django 5.0.9 on 2024-09-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('CarWashID', models.AutoField(primary_key=True, serialize=False)),
                ('NM_Number', models.CharField(max_length=255, unique=True)),
                ('CarWashName', models.CharField(max_length=255)),
                ('RegisteredBusinessName', models.CharField(max_length=255)),
                ('RegistrationNo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('ComplianceID', models.AutoField(primary_key=True, serialize=False)),
                ('CIPC', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('BusinessBankAccount', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('SARS_PIN', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('Ownership', models.CharField(choices=[('Private', 'Private'), ('Franchise', 'Franchise')], max_length=10)),
                ('CarWashID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarWashApp.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('JoiningID', models.AutoField(primary_key=True, serialize=False)),
                ('JoiningDate', models.DateField()),
                ('CarWashID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarWashApp.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('PhysicalAddress', models.CharField(max_length=255)),
                ('GPSCoordinates', models.CharField(max_length=50)),
                ('CityTownship', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('CarWashID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarWashApp.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('OwnerID', models.AutoField(primary_key=True, serialize=False)),
                ('OwnerNameSurname', models.CharField(max_length=255)),
                ('OwnerIDNumber', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=50)),
                ('EmailAddress', models.EmailField(max_length=255)),
                ('CarWashID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarWashApp.carwash')),
            ],
        ),
    ]
